### ISSUE TITLE
Combined hashtag support

### ISSUE THREAD

**Issue by angelix** [lmfresneda/mention-hashtag#1]
Is it possible to support combined hashtags, without spaces?

For example: #tag1#tag2#tag3
must return: [tag1 , tag2 , tag3]

Current version returns an empty array for this.

Thanks

**Comment by lmfresneda** [comment]
Thanks for the feedback angelix, it's interesting but, if you look at the code regex:

`/(?:^|[^a-zA-Z0-9_]+)(?:(?:#)(?!\/))([a-zA-Z0-9/_#]+)(?:\b(?!#)|$)/`

In an imaginary case, your example should return:

`['#tag1#tag2#tag3']`

That is, a single hashtag, not three, but in the real world a hashtag should not contain a `#` symbol. In fact, if you write on twitter:

`This is a #text#with#hashtag`

The result is text without hashtags. So, at the moment it is not possible to be done as you ask :)
